# Generated by Django 6.0.7 on 2026-07-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_At',
            field=models.DateTimeField(),
        ),
    ]
