# Generated by Django 5.0.6 on 2026-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
