# Generated by Django 6.0.6 on 2026-07-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plain_password',
        ),
    ]
