# Generated by Django 6.0.6 on 2026-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
